### ISSUE TITLE
Database Caddyfile configuration

### ISSUE THREAD

**Issue by l4nj1n9** [infogulch/xtemplate-caddy#6]
Final goal: get xtemplate to connect to a Postgres server.

First step: make it use a sqlite file, just to ensure that I understand the way config works (spoiler : no).

Inspired by this [Caddyfile](https://github.com/infogulch/todos/blob/master/Caddyfile) from your todos xtemplate-caddy sample app, I wrote [mine](https://github.com/PixyBlue/lazy-lob-web/blob/xtemplate-db/app.sample/Caddyfile) (in the context of [Lazy Lob Web (LLW) project](https://github.com/PixyBlue/lazy-lob-web)).
```
testxtemplate.localhost {
  tls internal
  route {
    xtemplate {
      templates_path /usr/share/caddy/templates
      database {
          driver sqlite
          connstr file:todos.db?_pragma=journal_mode(WAL)&_pragma=synchronous(1)&_pragma=foreign_keys(1)&_pragma=auto_vacuum(2)
      }
    }
  }
}
```
[Caddy was compiled this way](https://github.com/PixyBlue/lazy-lob-web/blob/xtemplate-db/app.sample/dockers/caddy/Dockerfile):
```
FROM caddy:builder-alpine AS builder

RUN xcaddy build \
  --with github.com/infogulch/xtemplate-caddy \
  --with github.com/WingLim/caddy-webhook \
  --with github.com/lib/pq

FROM caddy:alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
When I reload the Caddy configuration, I get:
```
Error: adapting config using caddyfile: parsing caddyfile tokens for 'route': parsing caddyfile tokens for 'xtemplate': unknown config option, at /etc/caddy/Caddyfile:20, at /etc/caddy/Caddyfile:25
```
The config option at `/etc/caddy/Caddyfile:20` is `database`...

Could tell what I'm doing wrong? What should I do to fix it?

**Comment by l4nj1n9** [comment]
Looking at https://github.com/infogulch/xtemplate-caddy/blob/master/caddyfile.go I wonder how you can handle database configuration...

**Comment by l4nj1n9** [comment]
@infogulch Is the project still alive ? It's been 5 months since the last commit (and 4 for the main xtemplate project)...

**Comment by infogulch** [comment]
Hi tao. I still intend to work on xtemplate, but I have less time to work on it recently due to a new job.

Yes, you correctly noticed that the current Caddyfile-based configuration is missing any way to configure dot extensions. However, it can still be configured using caddy json. I just published a new release in the xtemplate repo that includes a [test caddy.json](https://github.com/infogulch/xtemplate/blob/master/test/caddy.json).

I'm planning to update this repo soon, which may be a simple dep bump and then thoroughly updating the readme and examples.

Honestly its a bit of a conundrum because I don't see a simple way to ever fully support Caddyfile unless I abandon the extension idea and make sql, fs, and nats extensions non-optional / always compiled in. What do you think?

**Comment by l4nj1n9** [comment]
Hi Joe,

Congrats for your new job! I wish you to enjoy it. 

I was not aware of the json way to configure Caddy. I'll give it a try with xtemplate quickly.

Regarding sql, fs and nats, I can't figure any way to make them optional, except by separating them in distinct Caddy modules, which should certainly be a mess, and imply redundant code. But is it really necessary ? I mean: what are users looking for when they turn to xtemplate-caddy? Solutions that can't be built with Caddy alone, but without resorting to heavier means such as PHP. Offering them modularity could be interesting to get the greatest possible lightness. But, first, most modern applications use all three features concerned (database, filesystem, instant messaging) in one way or another, at one time or another. Moreover, xtemplate-caddy will always be lighter than PHP and the like.

If you really want to offer modularity, you could apply it to xtemplate alone for more advanced users with special scenarios.

Hope this helps.

**Comment by infogulch** [comment]
You're right. Maybe in some hypothetical future xtemplate will need to be highly extensible, but right now it needs to be focused.

**Comment by l4nj1n9** [comment]
Well, I struggled  a bit to handle json configuration of Caddy. I think it is a real pain to handle things this way, and I would not asked my users to do so. When do you expectto release a new version of xtemplate-caddy that will handle this the usual way ?

Never mind, now I'm struggling to query my database from templates.

Caddy was compiled using this Dockerfile:
```
FROM caddy:builder-alpine AS builder

RUN xcaddy build \
  --with github.com/infogulch/xtemplate-caddy \
  --with github.com/WingLim/caddy-webhook \
  --with github.com/jackc/pgx \
  --with github.com/greenpau/caddy-security \
  --with github.com/infogulch/xtemplate/providers \
  --with github.com/abiosoft/caddy-json-schema

FROM caddy:alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

Here is the Caddyfile.json:
```
{
  "logging": { "logs": { "default": { "level": "DEBUG" } } },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [":443"],
          "routes": [
            {
              "match": [{ "host": ["swagger.localhost"] }],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [{ "dial": "swagger:8080" }]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            },
            {
              "match": [{ "host": ["api.localhost"] }],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [{ "dial": "api:3000" }]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            },
            {
              "match": [{ "host": ["*.localhost", "localhost"] }],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        { "handler": "vars", "root": "/usr/share/caddy" },
                        {
                          "handler": "subroute",
                          "routes": [
                            {
                              "handle": [
                                {
                                  "handler": "xtemplate",
                                  "left": "{{",
                                  "right": "}}",
                                  "template_extension": ".html",
                                  "templates_dir": "/usr/share/caddy",
                                  "watch_context_path": false,
                                  "watch_template_path": true,
                                  "dot": [{
                                      "type": "sql",
                                      "name": "DB",
                                      "driver": "pgx",
                                      "connstr": "postgres://admin:p455w0rd@db:5432/db?sslmode=disable"
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        },
                        { "handler": "file_server", "hide": ["./Caddyfile"] }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    },
    "tls": {
      "automation": {
        "policies": [
          {
            "subjects": [
              "swagger.localhost",
              "api.localhost",
              "*.localhost",
              "localhost"
            ],
            "issuers": [{ "module": "internal" }]
          }
        ]
      }
    }
  }
}
```
Here, the template part where I try to query the database:
```
  <p>Hello, {{.Req.URL.Query.Get "name" | default "World"}}!</p>
  <hr>
  <ul>
    {{range .DB.Query `SELECT 1 as id,"toto" as name`}}
    <li><a href="/contact/{{.id}}">{{.name}}</a></li>
    {{end}}
  </ul>
```
The "Hello world" part alone works well, so, at least, Caddy is correctly configured to handle xtemplate. But when I add the DB.query part, I get an error:
```
web-1    | {"level":"warn","ts":1727874117.430668,"msg":"error executing template","xtemplate-caddy":{"xtemplate":{"instance":3,"serve":{"requestid":"4861361a-cb6d-422f-bec5-36fe98c0a849"},"error":"template: /index.html:16:15: executing \"/index.html\" at <.DB.Query>: can't evaluate field Query in type *providers.DotDB"}}}
```
Could you help? What am I doing wrong ?

**Comment by infogulch** [comment]
Ah there is no "Query" method anymore. Here's the docs for the DotDB provider: https://pkg.go.dev/github.com/infogulch/xtemplate/providers#DotDB

Here are the query methods:

- QueryVal
- QueryRow
- QueryRows

**Comment by l4nj1n9** [comment]
It works !
```
  <ul>
    {{range .DB.QueryRows `SELECT 1 as id,'toto' as name`}}
    <li><a href="/contact/{{.id}}">{{.name}}</a></li>
    {{end}}
  </ul>
  ```
  Thanks for your help !
  
  Btw, when do you expect to release a version that supports traditional Caddyfiles ? Do you want me to open another issue for that ?

**Comment by infogulch** [comment]
Congrats!

The issue is already created: https://github.com/infogulch/xtemplate-caddy/issues/5 Feel free to subscribe there, I will update that issue when I get to it. Maybe by next week.

The Caddyfile syntax is nicer on the eyes and is still well supported by caddy, but more than one module only supports json config, and the caddy author recommends json. It's a bit nested, but it's not too bad to use once you get used to it. Just something to think about.

Good luck with your project!
